-- CreateEnum
CREATE TYPE "TypeJob" AS ENUM ('FULL_TIME', 'PART_TIME', 'INTERN', 'CONTRACT', 'TEMPORARY', 'VOLUNTARY', 'PERMANENT', 'OTHER');

-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "type" "TypeJob" NOT NULL DEFAULT 'OTHER';
