-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'DELETED', 'BLOCKED', 'SUSPENDED', 'BANNED', 'DEACTIVATED', 'DEACTIVATED_PERMANENTLY', 'DEACTIVATED_TEMPORARILY', 'DEACTIVATED_BY_ADMIN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';
